import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
// import { createContext } from "react";

const inter = Inter({ subsets: ["latin"] });

type Theme = {
  colors: {
    primary: string
    secondary: string
  }
}

const defaultTheme: Theme = {
  colors: {
    primary: '#007bff',
    secondary: '#6c757d'
  }
}

const ThemeContext = createContext<Theme>(defaultTheme);

// export const metadata: Metadata = {
//   title: "Create Next App",
  // {
    // absolute: "",
    // default: "Next.js Tutorial",
    // template: "%s | Codevolution",
  // },
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
// Readonly<{
  children: React.ReactNode;
// }>
}) {
  return (
    <html lang="en">
      <ThemeContext.Provider value={defaultTheme}>
    <body>
    {/* // className={inter.className}>{children} */}
    <header
        style= {{
          backgroundColor: "lightblue",
          padding: "1rem",
        }}
        >
        <p>Header</p>
      </header>
      {children}
  <footer
      style={{
        backgroundColor: "ghostwhite",
        padding: "1rem",
      }}
      >
      <p>Footer</p>
    </footer>
    </body>
    </ThemeContext.Provider>
    </html>
  );
}
